#!/usr/bin/env python
"""Draws the conversation graph, from the graph rather than from memory.

    python -m tools.diagram          the mermaid that goes in the README
    python -m tools.diagram --nodes  just the node names, one per line

The picture in the README is generated by this, and a test compares the two, so
a node added to the graph and forgotten in the documentation fails the build
rather than quietly making the README wrong. A hand-drawn diagram of a graph is
accurate exactly once.
"""

from __future__ import annotations

import sys

from booking_agent.clinic.build import default
from booking_agent.conversation.graph import Agent
from booking_agent.conversation.reading import Rules


def graph():
    """The compiled graph, built against the clinic that ships with this."""
    clinic = default()
    agent = Agent(
        catalogue=clinic.catalogue,
        diary=clinic.diary,
        reader=Rules(clinic.catalogue),
    )
    return agent.drawn()


def nodes() -> list[str]:
    """Every node in the graph, without the two the library adds."""
    return sorted(
        name for name in graph().nodes if not name.startswith("__")
    )


def main(argv: list[str]) -> int:
    if "--nodes" in argv:
        print("\n".join(nodes()))
        return 0

    print(graph().draw_mermaid())
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
